FROM ubi8/ubi-minimal:8.3

# shadow-utils is needed for having adduser command
# unzip and curl is needed for deno install script
RUN microdnf install -y shadow-utils unzip curl && \
    microdnf clean all && \
    rm -rf /var/cache/yum && \
    useradd deno 

USER deno

RUN curl -fsSL https://deno.land/x/install/install.sh | sh
ENV DENO_INSTALL="/home/deno/.deno"
ENV PATH="$DENO_INSTALL/bin:$PATH"

WORKDIR /home/deno/app

CMD ["deno", "run",  "https://deno.land/std/examples/welcome.ts"]